FROM maven:3.9.4-eclipse-temurin-17 AS build

ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_RABBITMQ_HOST
ARG SPRING_RABBITMQ_USERNAME
ARG SPRING_RABBITMQ_PASSWORD
ARG SPRING_RABBITMQ_VIRTUAL_HOST
ARG GROQ_API_KEY
ARG GROQ_API_URL

ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
ENV SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}
ENV SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}
ENV SPRING_RABBITMQ_VIRTUAL_HOST=${SPRING_RABBITMQ_VIRTUAL_HOST}
ENV GROQ_API_KEY=${GROQ_API_KEY}
ENV GROQ_API_URL=${GROQ_API_URL}

WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -B -U clean package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar ./app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
